### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by RamyaKeerthana** [TwilioDevEd/appointment-reminders-rails#4]
sudo rake db:create db:migrate  is showing the following error

rake aborted!
Gem::LoadError: You have already activated rake 11.1.2, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/home/ramya/appointment-reminders-rails/config/boot.rb:3:in `<top (required)>'
/home/ramya/appointment-reminders-rails/config/application.rb:1:in `<top (required)>'
/home/ramya/appointment-reminders-rails/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/ramya/appointment-reminders-rails/config/boot.rb:3:in `<top (required)>'
/home/ramya/appointment-reminders-rails/config/application.rb:1:in `<top (required)>'
/home/ramya/appointment-reminders-rails/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Can any one please look into it

**Comment by acamino** [comment]
Thanks for reporting the issue. We'll update the README accordingly.

Nitpick: You don't need to run `rake db:create db:migrate` with `sudo`, it is not necessary.

In the meantime you can try as the error suggests.

```bash
bundle exec rake db:create db:migrate
```

**Comment by RamyaKeerthana** [comment]
'bundle exec rake db:create db:migrate' shows 
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.

So i ran : 'sudo bundle exec rake db:create db:migrate'
 Its showing the error  in the attached file

[error.txt](https://github.com/TwilioDevEd/appointment-reminders-rails/files/277669/error.txt)
